#!/usr/bin/env python3
"""Fetch true random integers from RANDOM.ORG using the official HTTP API.

You choose how many numbers and the inclusive range each time.
The values themselves are generated by RANDOM.ORG, not chosen locally.
"""

from __future__ import annotations

import argparse
import os
import sys
import urllib.error
import urllib.parse
import urllib.request
from typing import Iterable, Sequence

INTEGERS_URL = "https://www.random.org/integers/"
SEQUENCES_URL = "https://www.random.org/sequences/"
QUOTA_URL = "https://www.random.org/quota/"
REQUEST_TIMEOUT_SEC = 180
QUOTA_RETRY_SEC = 600
NUM_MIN, NUM_MAX = 1, 10_000
VALUE_MIN, VALUE_MAX = -1_000_000_000, 1_000_000_000


class RandomOrgError(RuntimeError):
    """RANDOM.ORG returned an error or the request was invalid."""


def user_agent() -> str:
    email = os.environ.get("RANDOM_ORG_EMAIL", "").strip()
    ident = "random-org-cli/1.0 (https://github.com/cuiyunfei0210/auto)"
    return f"{ident} {email}".strip()


def _get(url: str, params: dict[str, str]) -> str:
    query = urllib.parse.urlencode(params)
    request = urllib.request.Request(
        f"{url}?{query}",
        headers={"User-Agent": user_agent()},
        method="GET",
    )
    try:
        with urllib.request.urlopen(request, timeout=REQUEST_TIMEOUT_SEC) as response:
            body = response.read().decode("utf-8")
    except urllib.error.HTTPError as exc:
        body = exc.read().decode("utf-8", errors="replace")
        if "Error:" in body:
            first = next((line for line in body.splitlines() if line.startswith("Error:")), body.strip())
            raise RandomOrgError(first) from exc
        raise RandomOrgError(f"HTTP {exc.code}: {body.strip() or exc.reason}") from exc
    except urllib.error.URLError as exc:
        raise RandomOrgError(f"network error: {exc.reason}") from exc

    first = body.lstrip()
    if first.startswith("Error:"):
        raise RandomOrgError(body.splitlines()[0])
    return body


def parse_numbers(body: str) -> list[int]:
    numbers: list[int] = []
    for line in body.splitlines():
        line = line.strip()
        if not line:
            continue
        for token in line.split():
            numbers.append(int(token, 10))
    return numbers


def remaining_quota_bits() -> int:
    body = _get(QUOTA_URL, {"format": "plain"})
    return int(body.strip(), 10)


def generate_integers(num: int, minimum: int, maximum: int, *, unique: bool = False) -> list[int]:
    validate_range(num, minimum, maximum, unique=unique)
    quota = remaining_quota_bits()
    if quota < 0:
        raise RandomOrgError(
            f"RANDOM.ORG quota is exhausted ({quota} bits). "
            f"Wait about {QUOTA_RETRY_SEC // 60} minutes before requesting more."
        )

    if unique:
        sequence = parse_numbers(
            _get(
                SEQUENCES_URL,
                {
                    "min": str(minimum),
                    "max": str(maximum),
                    "col": "1",
                    "format": "plain",
                    "rnd": "new",
                },
            )
        )
        return sequence[:num]

    return parse_numbers(
        _get(
            INTEGERS_URL,
            {
                "num": str(num),
                "min": str(minimum),
                "max": str(maximum),
                "col": "1",
                "base": "10",
                "format": "plain",
                "rnd": "new",
            },
        )
    )


def validate_range(num: int, minimum: int, maximum: int, *, unique: bool) -> None:
    if not NUM_MIN <= num <= NUM_MAX:
        raise RandomOrgError(f"num must be between {NUM_MIN} and {NUM_MAX}")
    if not VALUE_MIN <= minimum <= VALUE_MAX:
        raise RandomOrgError(f"min must be between {VALUE_MIN} and {VALUE_MAX}")
    if not VALUE_MIN <= maximum <= VALUE_MAX:
        raise RandomOrgError(f"max must be between {VALUE_MIN} and {VALUE_MAX}")
    if minimum > maximum:
        raise RandomOrgError("min must be less than or equal to max")
    span = maximum - minimum + 1
    if unique and num > span:
        raise RandomOrgError(f"cannot pick {num} unique numbers from a range of {span}")
    if unique and span > NUM_MAX:
        raise RandomOrgError(f"unique mode requires max-min+1 <= {NUM_MAX}")


def prompt_int(label: str, default: int) -> int:
    raw = input(f"{label} [{default}]: ").strip()
    if not raw:
        return default
    try:
        return int(raw, 10)
    except ValueError as exc:
        raise RandomOrgError(f"invalid integer for {label}: {raw}") from exc


def prompt_yes(label: str, default: bool = False) -> bool:
    hint = "Y/n" if default else "y/N"
    raw = input(f"{label} [{hint}]: ").strip().lower()
    if not raw:
        return default
    return raw in {"y", "yes", "是"}


def format_numbers(numbers: Sequence[int], sep: str) -> str:
    return sep.join(str(n) for n in numbers)


def print_result(numbers: Iterable[int], sep: str) -> None:
    print(format_numbers(list(numbers), sep))


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate true random integers from RANDOM.ORG. "
        "Specify count and range each run; values come from RANDOM.ORG."
    )
    parser.add_argument("-n", "--num", type=int, help="how many integers to generate (1-10000)")
    parser.add_argument("--min", dest="minimum", type=int, help="inclusive lower bound")
    parser.add_argument("--max", dest="maximum", type=int, help="inclusive upper bound")
    parser.add_argument(
        "-u",
        "--unique",
        action="store_true",
        help="sample without replacement (no duplicate values)",
    )
    parser.add_argument(
        "--sep",
        default="\n",
        help="separator between numbers (default: newline)",
    )
    parser.add_argument("--quota", action="store_true", help="print remaining bit quota and exit")
    parser.add_argument(
        "-i",
        "--interactive",
        action="store_true",
        help="prompt for num/min/max even if some flags are set",
    )
    return parser


def resolve_params(args: argparse.Namespace) -> tuple[int, int, int, bool]:
    need_prompt = args.interactive or args.num is None or args.minimum is None or args.maximum is None
    if need_prompt and not sys.stdin.isatty() and (args.num is None or args.minimum is None or args.maximum is None):
        raise RandomOrgError("num, min, and max are required in non-interactive mode")

    if need_prompt and sys.stdin.isatty() and (args.num is None or args.minimum is None or args.maximum is None or args.interactive):
        print("RANDOM.ORG true random integers")
        print("Each run you specify count and range; RANDOM.ORG generates the values.\n")
        num = args.num if args.num is not None else prompt_int("count", 1)
        minimum = args.minimum if args.minimum is not None else prompt_int("min", 1)
        maximum = args.maximum if args.maximum is not None else prompt_int("max", 100)
        unique = args.unique or prompt_yes("unique (no duplicates)", False)
        return num, minimum, maximum, unique

    if args.num is None or args.minimum is None or args.maximum is None:
        raise RandomOrgError("provide --num, --min, and --max, or run without flags for prompts")
    return args.num, args.minimum, args.maximum, args.unique


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        if args.quota:
            print(remaining_quota_bits())
            return 0
        num, minimum, maximum, unique = resolve_params(args)
        numbers = generate_integers(num, minimum, maximum, unique=unique)
        print_result(numbers, args.sep)
        return 0
    except KeyboardInterrupt:
        print("\naborted", file=sys.stderr)
        return 130
    except RandomOrgError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
